name: Auto push to develop-in-home on develop update

on:
     push:
         branches:
             - development1

jobs:
     rebase-in-home:
         runs-on: ubuntu-latest
         steps:
             - name: Checkout
               uses: actions/checkout@v1 
             - name: Rebase in-home
               run: scripts/git-rebase
             - name: Push rebased in-home
               uses: ad-m/github-push-action@master
               with:
                   branch: master
                   github_token: ${{ secrets.GITHUB_TOKEN }}
